# Generated by Django 4.2.7 on 2023-11-26 16:17
"""
Database migration to remove the 'id' field from the 'Offer' model and add 'offer_id' as the primary key.

    Dependencies:
    - 'properties' app's migration '0008_remove_property_country_remove_property_name_and_more'.

    Operations:
    - Remove the 'id' field from the 'Offer' model.
    - Add 'offer_id' as the primary key for the 'Offer' model.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_remove_property_country_remove_property_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='id',
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
